apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: data-lighthouse-reader
  labels:
    {{- include "data-lighthouse.labels" . | nindent 4 }}
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["scheduling.volcano.sh"]
    resources: ["queues", "jobs"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-lighthouse-reader
  labels:
    {{- include "data-lighthouse.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: data-lighthouse-reader
subjects:
  - kind: ServiceAccount
    name: data-lighthouse
    namespace: data-lighthouse
