apiVersion: v1
kind: Secret
metadata:
  name: vdp-portal-env
  labels:
    {{- include "vdp-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_ISSUER: "{{ .Values.keycloak.issuer }}"
  KEYCLOAK_CLIENT_ID: "{{ .Values.keycloak.clientId }}"
  KEYCLOAK_CLIENT_SECRET: "{{ .Values.keycloak.clientSecret }}"
  NEXTAUTH_URL: "https://portal.lakehouse.local"
  NEXTAUTH_SECRET: "{{ .Values.nextauth.secret }}"
  NEXT_PUBLIC_APP_NAME: "VDP Portal"
